-- =======================================================
-- MIGRATION: Add Task Assignments System
-- Run this in Supabase SQL Editor to update your existing database
-- =======================================================

-- Create task_assignments table
-- This allows assigning tasks to specific kids and/or specific dates
CREATE TABLE IF NOT EXISTS public.task_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT REFERENCES public.tasks(id) ON DELETE CASCADE NOT NULL,
  kid_id BIGINT, -- NULL means assigned to ALL kids
  assigned_date TEXT, -- NULL means assigned to ALL dates (recurring daily)
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable RLS
ALTER TABLE public.task_assignments ENABLE ROW LEVEL SECURITY;

-- Create policy
CREATE POLICY "Allow all on assignments" ON public.task_assignments FOR ALL USING (true) WITH CHECK (true);

-- Create index for faster queries
CREATE INDEX IF NOT EXISTS idx_task_assignments_lookup 
ON public.task_assignments(task_id, kid_id, assigned_date);
