CREATE TABLE IF NOT EXISTS public.task_assignments (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  task_id BIGINT REFERENCES public.tasks(id) ON DELETE CASCADE NOT NULL,
  kid_id BIGINT,
  assigned_date TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

ALTER TABLE public.task_assignments ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow all on assignments" ON public.task_assignments FOR ALL USING (true) WITH CHECK (true);

INSERT INTO public.task_assignments (task_id, kid_id, assigned_date)
SELECT id, NULL, NULL
FROM public.tasks
WHERE id NOT IN (SELECT task_id FROM public.task_assignments);
