-- =======================================================
-- DREAM OF JANNAH - SUPABASE SQL SCHEMA
-- Copy and paste this script directly into your Supabase SQL Editor!
-- =======================================================

-- 1. Create kids table
CREATE TABLE IF NOT EXISTS public.kids (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  avatar TEXT NOT NULL,
  points INTEGER DEFAULT 0,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 2. Create tasks table
CREATE TABLE IF NOT EXISTS public.tasks (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  title TEXT NOT NULL,
  points INTEGER NOT NULL,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- 3. Create task_completions table
CREATE TABLE IF NOT EXISTS public.task_completions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  kid_id BIGINT REFERENCES public.kids(id) ON DELETE CASCADE NOT NULL,
  task_id BIGINT REFERENCES public.tasks(id) ON DELETE CASCADE NOT NULL,
  completed_date TEXT NOT NULL, -- e.g., "YYYY-MM-DD"
  points_earned INTEGER NOT NULL
);

-- 4. Create champions table (monthly Hall of Fame)
CREATE TABLE IF NOT EXISTS public.champions (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  month TEXT NOT NULL,
  champion_name TEXT NOT NULL,
  champion_avatar TEXT NOT NULL,
  champion_points INTEGER NOT NULL,
  runner_up_name TEXT,
  runner_up_avatar TEXT,
  runner_up_points INTEGER,
  declared_at TIMESTAMP WITH TIME ZONE DEFAULT TIMEZONE('utc'::text, NOW()) NOT NULL
);

-- Enable Row Level Security (RLS) but allow everyone read/write
-- Since this is a simple family utility, we disable active locking or open up rules so anyone's Chrome can read/write.
ALTER TABLE public.kids ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.tasks ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.task_completions ENABLE ROW LEVEL SECURITY;
ALTER TABLE public.champions ENABLE ROW LEVEL SECURITY;

-- Create Open Policies (allows anyone to read/write without complex logins)
CREATE POLICY "Allow all on kids" ON public.kids FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on tasks" ON public.tasks FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on completions" ON public.task_completions FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Allow all on champions" ON public.champions FOR ALL USING (true) WITH CHECK (true);

-- Prepopulate Default Jannah Deed Tasks (Bangla / English)
INSERT INTO public.tasks (title, points) VALUES 
('আজকে সঠিক সময়ে নামাজ আদায় করা 🕌', 15),
('বাবা-মাকে হাসিমুখে সাহায্য করা 💖', 10),
('সকাল ও রাতে নিয়ম করে দাঁত ব্রাশ করা 🦷', 10),
('একটি ভালো বই অথবা শিক্ষণীয় গল্প পড়া 📖', 15),
('নিজের রুম ও খেলার জিনিস গুছিয়ে রাখা 🧹', 10),
('আজকের স্কুলের হোমওয়ার্ক শেষ করা 📝', 15),
('কারো সাথে নিজের খেলনা বা খাবার শেয়ার করা 🧸', 10)
ON CONFLICT DO NOTHING;
